Repository one-acre-fund/oaf-public-charts, pull requests merged in 2021-07, with the labels that each got.

#14 fineract helmchart
  charts/apicurio/Chart.yaml
  charts/apicurio/README.md
  charts/apicurio/values.yaml
  charts/fineract/Chart.yaml
  charts/fineract/NOTES.txt
  charts/fineract/README.md
  charts/fineract/README.md.gotmpl
  charts/fineract/ci/ci-values.yaml
  charts/fineract/ci/qa.yaml
  charts/fineract/requirements.lock
  charts/fineract/templates/_helpers.tpl
  charts/fineract/templates/activemq-configmap.yaml
  charts/fineract/templates/activemq-service.yaml
  charts/fineract/templates/activemq-statefulset.yaml
  charts/fineract/templates/fineract-ingress.yaml
  charts/fineract/templates/fineract-job-service.yaml
  charts/fineract/templates/fineract-job-statefulset.yaml
  charts/fineract/templates/fineract-job-ui-deployment.yaml
  charts/fineract/templates/fineract-job-ui-ingress.yaml
  charts/fineract/templates/fineract-job-ui-service.yaml
  charts/fineract/templates/fineract-mifosx-deployment.yml
  charts/fineract/templates/fineract-mifosx-svc.yml
  charts/fineract/templates/fineract-report-service.yaml
  charts/fineract/templates/fineract-report-statefulset.yaml
  charts/fineract/templates/fineract-report-ui-deployment.yaml
  charts/fineract/templates/fineract-report-ui-ingress.yaml
  charts/fineract/templates/fineract-report-ui-service.yaml
  charts/fineract/templates/fineract-rest-service.yaml
  charts/fineract/templates/fineract-rest-statefulset.yaml
  charts/fineract/templates/fineract-rest-ui-deployment.yaml
  charts/fineract/templates/fineract-rest-ui-ingress.yaml
  charts/fineract/templates/fineract-rest-ui-service.yaml
  charts/fineract/templates/fineract-secret.yaml
  charts/fineract/templates/fineract-server-deployment.yml
  charts/fineract/templates/fineract-server-svc.yml
  charts/fineract/templates/fineract-ui-deployment.yml
  charts/fineract/templates/fineract-ui-svc.yml
  charts/fineract/templates/hpa.yaml
  charts/fineract/templates/persistentVolume/fineract-job-pvc.yaml
  charts/fineract/templates/persistentVolume/fineract-report-pvc.yaml
  charts/fineract/templates/persistentVolume/fineract-rest-pvc.yaml
  charts/fineract/templates/tests/test-fineract.yaml
  charts/fineract/values.yaml
Labels: size/XXL

#15 changed access Modes
  charts/fineract/Chart.yaml
  charts/fineract/README.md
  charts/fineract/templates/persistentVolume/fineract-job-pvc.yaml
  charts/fineract/templates/persistentVolume/fineract-report-pvc.yaml
  charts/fineract/templates/persistentVolume/fineract-rest-pvc.yaml
Labels: size/S

#16 reverted to readwritemany
  charts/fineract/Chart.yaml
  charts/fineract/README.md
  charts/fineract/templates/persistentVolume/fineract-job-pvc.yaml
  charts/fineract/templates/persistentVolume/fineract-report-pvc.yaml
  charts/fineract/templates/persistentVolume/fineract-rest-pvc.yaml
Labels: size/S

#17 adding mysql
  charts/fineract/Chart.yaml
  charts/fineract/README.md
  charts/fineract/ci/qa.yaml
  charts/fineract/templates/_helpers.tpl
  charts/fineract/templates/fineract-job-statefulset.yaml
  charts/fineract/templates/fineract-report-statefulset.yaml
  charts/fineract/templates/fineract-rest-statefulset.yaml
  charts/fineract/templates/fineract-secret.yaml
  charts/fineract/values.yaml
Labels: size/L
