Repository one-acre-fund/oaf-public-charts, pull requests merged in 2022-09, with the labels that each got.

#78 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/XS

#79 add kobocat azure storage
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/values.yaml
Labels: size/S

#80 fix spacing
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/values.yaml
Labels: size/S

#81 debug
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/S

#82 restore original commands
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/S

#83 add lazy-apps to kobocat as well
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/XS

#84 add uwsgi metrics exporter
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/metrics-exporter.yaml
Labels: size/M

#85 fix exporter arguments
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/metrics-exporter.yaml
Labels: size/XS

#86 add exporter as a sidecar
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
  charts/kobotoolbox/templates/metrics-exporter.yaml
Labels: size/M

#90 delete fineract chart
  charts/fineract/.helmignore
  charts/fineract/Chart.yaml
  charts/fineract/NOTES.txt
  charts/fineract/README.md
  charts/fineract/README.md.gotmpl
  charts/fineract/ci/ci-values.yaml
  charts/fineract/requirements.lock
  charts/fineract/templates/_helpers.tpl
  charts/fineract/templates/fineract-ingress.yaml
  charts/fineract/templates/fineract-mifosx-deployment.yml
  charts/fineract/templates/fineract-mifosx-svc.yml
  charts/fineract/templates/fineract-secret.yaml
  charts/fineract/templates/fineract-server-deployment.yml
  charts/fineract/templates/fineract-server-svc.yml
  charts/fineract/templates/fineract-ui-deployment.yml
  charts/fineract/templates/fineract-ui-svc.yml
  charts/fineract/templates/tests/test-fineract.yaml
  charts/fineract/values.yaml
Labels: size/XL

#91 upgrade flagsmith keycloak
  charts/apicurio/Chart.yaml
  charts/apicurio/README.md
  charts/flagsmith/Chart.lock
  charts/flagsmith/Chart.yaml
  charts/flagsmith/README.md
Labels: size/S

#92 bump versions
  charts/growthbook/Chart.lock
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/metabase/Chart.yaml
  charts/metabase/README.md
  charts/n8n/Chart.yaml
  charts/n8n/README.md
  charts/nocodb/Chart.lock
  charts/nocodb/Chart.yaml
  charts/nocodb/README.md
Labels: size/M

#93 fix syntax
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#94 fix syntax
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#95 fix syntax
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#96 re-add init container command
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/S

#97 remove quotes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#98 try downgrading dependency
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#99 Fix/kobo crashes
  .github/workflows/helm-test.yaml
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/S

#100 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-conf.yaml
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#101 chain commands
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/S

#102 fix chaining
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#103 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/XS

#104 change uwsgi ini mount pathe
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#110 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
  charts/kobotoolbox/templates/kobo-deploy.yaml
  charts/kobotoolbox/templates/kobo-postgres-init.yaml
  charts/kobotoolbox/values.yaml
Labels: size/L

#111 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/values.yaml
Labels: size/M

#112 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#113 use tcp for metrics
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
Labels: size/XS

#114 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
  charts/kobotoolbox/templates/kobo-svc.yaml
  charts/kobotoolbox/templates/metrics-exporter.yaml
  charts/kobotoolbox/values.yaml
Labels: size/M

#115 fix listening port
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/metrics-exporter.yaml
Labels: size/S

#116 increase default respawn thresholds
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
Labels: size/XS

#117 increase default rss respawn memory threshold
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/XS

#118 increase default min worker lifespan
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/S

#119 Fix/kobo crashes
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/S

#121 increase workers
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
Labels: size/XS

#122 disbale cheaper algorithm
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/M

#123 increase worker lifetime
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/S

#124 disable respawning
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-conf.yaml
Labels: size/M

#126 kobo: env var cleanup
  .gitignore
  charts/kobotoolbox/Chart.lock
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/charts/mongodb-12.1.20.tgz
  charts/kobotoolbox/charts/postgresql-11.6.6.tgz
  charts/kobotoolbox/charts/redis-16.12.2.tgz
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-conf.yaml
  charts/kobotoolbox/templates/kobo-deploy.yaml
  charts/kobotoolbox/templates/kobo-postgres-init.yaml
  charts/kobotoolbox/templates/kobo-secrets.yaml
  charts/kobotoolbox/values.yaml
Labels: size/XL
