Repository one-acre-fund/oaf-public-charts, pull requests merged in 2022-06, with the labels that each got.

#62 Growthbook chart
  .github/workflows/helm-test.yaml
  README.md
  charts/growthbook/Chart.lock
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/growthbook/templates/_helpers.tpl
  charts/growthbook/templates/deployment.yaml
  charts/growthbook/templates/hpa.yaml
  charts/growthbook/templates/ingress.yaml
  charts/growthbook/templates/pvc.yaml
  charts/growthbook/templates/service.yaml
  charts/growthbook/templates/serviceaccount.yaml
  charts/growthbook/values.yaml
Labels: size/XL

#63 Growthbook chart update
  .github/workflows/helm-release.yaml
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/growthbook/templates/deployment.yaml
  charts/growthbook/templates/pvc.yaml
  charts/growthbook/values.yaml
Labels: size/M

#64 Feature/growthbook
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/growthbook/templates/deployment.yaml
Labels: size/M

#65 change mount name
  charts/growthbook/Chart.yaml
  charts/growthbook/templates/deployment.yaml
Labels: size/XS

#66 Growthbook chart update
  charts/growthbook/Chart.lock
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/growthbook/templates/_helpers.tpl
  charts/growthbook/templates/deployment.yaml
  charts/growthbook/templates/secrets.yaml
  charts/growthbook/values.yaml
Labels: size/M

#70 Feature/kobo
  .github/workflows/helm-release.yaml
  charts/kobotoolbox/Chart.lock
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/_helpers.tpl
  charts/kobotoolbox/templates/kobo-secrets.yaml
  charts/kobotoolbox/values.yaml
Labels: size/M
