Repository one-acre-fund/oaf-public-charts, pull requests merged in 2022-11, with the labels that each got.

#129 Growthbook single-sign-on support
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/growthbook/templates/deployment.yaml
  charts/growthbook/templates/secrets.yaml
  charts/growthbook/values.yaml
Labels: size/M

#130 Fix Growthbook license and smtp password secrets
  charts/growthbook/Chart.yaml
  charts/growthbook/templates/deployment.yaml
  charts/growthbook/templates/secrets.yaml
Labels: size/S

#131 Growthbook clean up
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/growthbook/templates/deployment.yaml
  charts/growthbook/templates/secrets.yaml
  charts/growthbook/values.yaml
Labels: size/M

#132 add kutt helm chart
  charts/kutt/.helmignore
  charts/kutt/Chart.yaml
  charts/kutt/templates/NOTES.txt
  charts/kutt/templates/_helpers.tpl
  charts/kutt/templates/deployment.yaml
  charts/kutt/templates/hpa.yaml
  charts/kutt/templates/ingress.yaml
  charts/kutt/templates/service.yaml
  charts/kutt/templates/serviceaccount.yaml
  charts/kutt/templates/tests/test-connection.yaml
  charts/kutt/values.yaml
Labels: size/L

#134 bump version
  charts/kutt/Chart.yaml
  charts/kutt/README.md
Labels: size/M

#135 Fix/kutt
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/config.yaml
  charts/kutt/templates/secret.yaml
  charts/kutt/values.yaml
Labels: size/M

#136 remove configmap
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/config.yaml
  charts/kutt/templates/deployment.yaml
  charts/kutt/values.yaml
Labels: size/M

#137 quote strings
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/deployment.yaml
Labels: size/XS

#138 add secrets
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/deployment.yaml
  charts/kutt/templates/secret.yaml
Labels: size/XS

#139 change container port
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/deployment.yaml
Labels: size/XS

#140 Fix/kutt
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/deployment.yaml
  charts/kutt/templates/service.yaml
Labels: size/S

#141 remove main port
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/deployment.yaml
  charts/kutt/templates/service.yaml
Labels: size/S

#144 Fix/kutt
  charts/growthbook/Chart.yaml
  charts/growthbook/README.md
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/secret.yaml
  charts/kutt/values.yaml
  charts/n8n/Chart.yaml
  charts/n8n/README.md
  charts/nocodb/Chart.yaml
  charts/nocodb/README.md
Labels: size/M

#145 remove sentry dsn from secrets
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/values.yaml
  charts/n8n/Chart.yaml
  charts/n8n/README.md
Labels: size/S

#146 disable recaptcha
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/values.yaml
Labels: size/S

#147 disable secret quoting
  charts/kutt/Chart.yaml
  charts/kutt/README.md
  charts/kutt/templates/secret.yaml
  charts/kutt/values.yaml
Labels: size/S

#148 Fix/kobo priority
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-deploy.yaml
  charts/kobotoolbox/values.yaml
Labels: size/XS
