Repository one-acre-fund/oaf-public-charts, pull requests merged in 2023-01, with the labels that each got.

#150 add optional flower monitoring of tasks
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-flower.yaml
  charts/kobotoolbox/values.yaml
Labels: size/L

#151 hide secret
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-flower.yaml
Labels: size/S

#152 fix redis port
  charts/kobotoolbox/Chart.yaml
  charts/kobotoolbox/README.md
  charts/kobotoolbox/templates/kobo-flower.yaml
Labels: size/XS

#149 chore(docs): add n8n, improve markup
  README.md
Labels: size/XS
