Repository one-acre-fund/oaf-public-charts, pull requests merged in 2024-10, with the labels that each got.

#196 chore: Update nocodb chart with new icon and sources
  charts/nocodb/Chart.yaml
  charts/nocodb/README.md
  charts/nocodb/README.md.gotmpl
  charts/nocodb/img/icon.png
Labels: size/S

#187 fix(Mautic Ingress): Resolved Invalid PathType and Service Backend
  charts/mautic/Chart.yaml
  charts/mautic/templates/ingress.yaml
Labels: size/XS

#197 Merge index page from gh-pages branch
  index.yaml
Labels: size/XXL

#198 chore: Add GitHub Pages workflow for Jekyll site deployment
  .github/workflows/gh-pages.yml
Labels: size/M

#199 chore: Update destination path for GitHub Pages workflow
  .github/workflows/gh-pages.yml
Labels: size/XS

#200 chore: Update destination path for GitHub Pages workflow
  .github/workflows/gh-pages.yml
Labels: size/XS

#203 Refactor NocoDB Helm Chart to increase configurability
  charts/nocodb/Chart.yaml
  charts/nocodb/templates/configmap.yaml
  charts/nocodb/templates/deployment.yaml
  charts/nocodb/templates/secrets.yaml
  charts/nocodb/values.yaml
Labels: size/M

#204 Update NocoDB Helm Chart: Secret Management Enhancements
  charts/nocodb/Chart.yaml
  charts/nocodb/README.md
  charts/nocodb/templates/_helpers.tpl
  charts/nocodb/templates/admin-user-secert.yaml
  charts/nocodb/templates/deployment.yaml
  charts/nocodb/templates/smtp-secret.yaml
Labels: size/L

#205 Refactor nocodb template variable names for minio secret
  charts/nocodb/Chart.yaml
  charts/nocodb/README.md
  charts/nocodb/templates/_helpers.tpl
Labels: size/S

#206 fix(helm): quote databasePort to fix unmarshal error
  charts/nocodb/Chart.yaml
  charts/nocodb/README.md
  charts/nocodb/templates/deployment.yaml
  charts/nocodb/values.yaml
Labels: size/S
